package com.myspace.kafka;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class payload implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public payload() {
    }




}